### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by lepriko** [ChenyangLEI/All-In-One-Deflicker#16]
Hi guys, 
I'm really excited to test the awesome software that you've created.
Can someone help me to install it on a Windows machine, when I try to install it using Conda the packages are missing. I got:

> 
(base) PS D:\proj\All-in-one-Deflicker> conda env create --name deflicker -f environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: failed

> 

ResolvePackageNotFound:
  - lame==3.100=h166bdaf_1003
  - libzlib==1.2.13=h166bdaf_4
  - libpng==1.6.39=h753d276_0
  - blas-devel==3.9.0=16_linux64_mkl
  - xorg-xproto==7.0.31=h7f98852_1007
  - lerc==4.0.0=h27087fc_0
  - libdrm==2.4.114=h166bdaf_0
  - ca-certificates==2022.12.7=ha878542_0
  - libnsl==2.0.0=h7f98852_0
  - ffmpeg==5.1.2=gpl_h8dda1f0_106
  - numpy==1.24.2=py310h8deb116_0
  - p11-kit==0.24.1=hc5aa10d_0
  - pillow==9.4.0=py310h023d228_1
  - libblas==3.9.0=16_linux64_mkl
  - xorg-fixesproto==5.0=h7f98852_1002
  - openjpeg==2.5.0=hfec8fc6_2
  - libuuid==2.32.1=h7f98852_1000
  - libwebp-base==1.3.0=h0b41bf4_0
  - readline==8.1.2=h0f457ee_0
  - svt-av1==1.4.1=hcb278e6_0
  - python==3.10.9=he550d4f_0_cpython
  - lcms2==2.15=hfd0df8a_0
  - mkl==2022.1.0=h84fe81f_915
  - x265==3.5=h924138e_3
  - gmp==6.2.1=h58526e2_0
  - xorg-libxau==1.0.9=h7f98852_0
  - fontconfig==2.14.2=h14ed4e7_0
  - tbb==2021.8.0=hf52228f_0
  - libgfortran5==12.2.0=h337968e_19
  - _openmp_mutex==4.5=2_kmp_llvm
  - openh264==2.3.1=hcb278e6_2
  - libsqlite==3.40.0=h753d276_0
  - tk==8.6.12=h27826a3_0
  - openssl==3.1.0=h0b41bf4_0
  - aom==3.5.0=h27087fc_0
  - icu==70.1=h27087fc_0
  - bzip2==1.0.8=h7f98852_4
  - xorg-libxdmcp==1.1.3=h7f98852_0
  - mkl-include==2022.1.0=h84fe81f_915
  - llvm-openmp==15.0.7=h0cdce71_0
  - libunistring==0.9.10=h7f98852_0
  - xorg-xextproto==7.3.0=h0b41bf4_1003
  - libiconv==1.17=h166bdaf_0
  - libopus==1.3.1=h7f98852_1
  - libtasn1==4.19.0=h166bdaf_0
  - x264==1!164.3095=h166bdaf_2
  - mkl-devel==2022.1.0=ha770c72_916
  - xorg-libxext==1.3.4=h0b41bf4_2
  - libhwloc==2.9.0=hd6dc26d_0
  - libxcb==1.13=h7f98852_1004
  - libxml2==2.10.3=h7463322_0
  - libcblas==3.9.0=16_linux64_mkl
  - pthread-stubs==0.4=h36c2ea0_1001
  - xorg-kbproto==1.0.7=h7f98852_1002
  - xorg-libxfixes==5.0.3=h7f98852_1004
  - nettle==3.8.1=hc379101_1
  - ncurses==6.3=h27087fc_1
  - libgcc-ng==12.2.0=h65d4601_19
  - xz==5.2.6=h166bdaf_0
  - libdeflate==1.17=h0b41bf4_0
  - liblapack==3.9.0=16_linux64_mkl
  - libva==2.17.0=h0b41bf4_0
  - libgfortran-ng==12.2.0=h69a702a_19
  - libtiff==4.5.0=h6adf6a1_2
  - _libgcc_mutex==0.1=conda_forge
  - libvpx==1.11.0=h9c3ff4c_3
  - xorg-libx11==1.8.4=h0b41bf4_0
  - libffi==3.4.2=h7f98852_5
  - gnutls==3.7.8=hf3e180e_0
  - freetype==2.12.1=hca18f0e_1
  - jpeg==9e=h0b41bf4_3
  - ld_impl_linux-64==2.40=h41732ed_0
  - zstd==1.5.2=h3eb15da_6
  - cudatoolkit==11.3.1=h9edb442_11
  - libpciaccess==0.17=h166bdaf_0
  - cffi==1.15.1=py310h255011f_3
  - libidn2==2.3.4=h166bdaf_0
  - pytorch==1.12.0=py3.10_cuda11.3_cudnn8.3.2_0
  - cryptography==39.0.2=py310h34c0648_0
  - libstdcxx-ng==12.2.0=h46fd767_19
  - expat==2.5.0=h27087fc_0
  - liblapacke==3.9.0=16_linux64_mkl
  - gettext==0.21.1=h27087fc_0
  - brotlipy==0.7.0=py310h5764c6d_1005

Already tried to remove the version after the second = but with no luck so far. 
Does anyone have an environment.yml that is compatible with Windows? 
Any help will be appreciated.

**Comment by ronruizG** [comment]
yeah this doesn't have the env for a windows installation :(

**Comment by deklesen** [comment]
Any solution to this?

**Comment by Cornox** [comment]
I got it working using anaconda:

*open anaconda and set your desired download location for the github depository:

cd C:\Users\USERNAME\Documents\github
git clone https://github.com/ChenyangLEI/All-In-One-Deflicker.git
cd All-In-One-Deflicker



*create anaconda environment using the provided yml file:

conda env create -f environment.yml
conda activate deflicker



*download checkpoint and move, remove some folders:

git clone https://github.com/ChenyangLEI/cvpr2023_deflicker_public_folder
mv cvpr2023_deflicker_public_folder/pretrained_weights ./ && rm -r cvpr2023_deflicker_public_folder
*press y, then enter to confirm
*press y, then enter to confirm again



*install packages to get rid of the error codes:

pip install opencv-python
pip install tensorboard
pip install easydict
pip install imageio-ffmpeg


*copy your input video to ....All-In-One-Deflicker\data\test:

*Inference (set the FPS to match your input video):

set PYTHONPATH=%cd%
python test.py --video_name data/test/please_deflicker_me.mp4 --fps 25

**Comment by nixudos** [comment]
Cornox; how do you get past the conda env create -f environment.yml?
It fails on mine with Miniconda and refuses to activate.
Do we just ignore and continue to run the pip installs?
Or are you on a WSL?

**Comment by Cornox** [comment]
I don't know what happened but my anaconda environment is gone today. I didn't delete it and it's not in the recycle bin, It's just gone. Yesterday I was able to just use the prvovided environment.yml to install the env and I ran the deflickering twice succesfully. Today after trying to re-install then env using the yml file I get the "Solving environment: failed" error aswell.

Ignoring the error doesn't work since there's no environemt installed (and no packages that are listed in the env.yml) so I can't activate it or proceed.

I don't know what WSL is so I guess that's a No.

I'm now troubleshooting anaconda with the help of chatGPT.

**Comment by Cornox** [comment]
The yaml file doesn't work. (I didn't paid attention and the env was enver created for me and aI also didn't activate any new environmant)
I installed packages into my base env by accident and got lucky to get it running since my base env had pytorch and other packages installed from previous acciental installs of stable diffusion into the base env :(.
Since the requirments of SD and deflicker overlap to some dagree I accendentially got it running, I only had to install opencv-python, tensorboard, easydict, imageio-ffmpeg additionally.

I guess if you have a stable diffusion envrionment you could use that one and install the packages I listed above.

**Comment by Cornox** [comment]
Updated install instructions (without using the environment.yml):
conda create --name deflicker python=3.8.8
conda activate deflicker

git clone https://github.com/ChenyangLEI/All-In-One-Deflicker.git
cd All-In-One-Deflicker
git clone https://github.com/ChenyangLEI/cvpr2023_deflicker_public_folder
move cvpr2023_deflicker_public_folder\pretrained_weights .\ && rmdir /s /q cvpr2023_deflicker_public_folder

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

*create a new text document called requirements and paste the following lines in it (without the -------) and save it in the "All-In-One-Deflicker" folder: 
---------------------------------
brotlipy==0.7.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==39.0.2
ffmpeg
icu
idna
opencv-python
tensorboard
easydict
imageio-ffmpeg
imageio
tqdm
matplotlib
scikit-image
ffmpeg
------------------------------

pip install -r requirements.txt

*place your video in "All-In-One-Deflicker\data\test"
*Inference:
set PYTHONPATH=%cd%
python test.py --video_name data/test/Winter_Scenes_in_Holland.mp4 --fps 10

*I recommend using a video with dimensions that are a multiple of 64 to avoid getting your output video squashed mildly.

**Comment by konfalkon** [comment]
Followed instructions above and I have this after running:

`Traceback (most recent call last):
  File "E:\deflicker\src\stage1_neural_atlas.py", line 10, in <module>
    from src.models.stage_1.implicit_neural_networks import IMLP
ModuleNotFoundError: No module named 'src'
Traceback (most recent call last):
  File "E:\deflicker\src\neural_filter_and_refinement.py", line 6, in <module>
    import src.models.network_filter as net
ModuleNotFoundError: No module named 'src'`

**Comment by pablx-ts** [comment]
I get this error.

(deflicker) F:\apps\All-In-One-Deflicker>python test.py --video_frame_folder data/test/ause/
Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', class_name=None, fps=10, gpu=0, video_frame_folder='data/test/ause/', video_name=None)
input folder ./data/test/ exist
usage: stage1_neural_atlas.py [-h] [--config CONFIG] [--vid_name VID_NAME] [--root ROOT] [--down DOWN] [--gpu GPU]
stage1_neural_atlas.py: error: argument --vid_name: expected one argument
usage: neural_filter_and_refinement.py [-h] [--ckpt_filter CKPT_FILTER] [--ckpt_local CKPT_LOCAL] [--fps FPS] [--video_name VIDEO_NAME] [--gpu GPU]
neural_filter_and_refinement.py: error: argument --video_name: expected one argument

**Comment by Sirfalus** [comment]
> Followed instructions above and I have this after running:
> 
> `Traceback (most recent call last): File "E:\deflicker\src\stage1_neural_atlas.py", line 10, in <module> from src.models.stage_1.implicit_neural_networks import IMLP ModuleNotFoundError: No module named 'src' Traceback (most recent call last): File "E:\deflicker\src\neural_filter_and_refinement.py", line 6, in <module> import src.models.network_filter as net ModuleNotFoundError: No module named 'src'`

Have you found the solution? I also got this same problem, still have not figured it out yet.

**Comment by konfalkon** [comment]
> > Followed instructions above and I have this after running:
> > `Traceback (most recent call last): File "E:\deflicker\src\stage1_neural_atlas.py", line 10, in <module> from src.models.stage_1.implicit_neural_networks import IMLP ModuleNotFoundError: No module named 'src' Traceback (most recent call last): File "E:\deflicker\src\neural_filter_and_refinement.py", line 6, in <module> import src.models.network_filter as net ModuleNotFoundError: No module named 'src'`
> 
> Have you found the solution? I also got this same problem, still have not figured it out yet.

Solution is to remove prefix src from every line of code where it occurs. For example src.models.network_filter -> models.network_filter.

**Comment by Sirfalus** [comment]
> > > Followed instructions above and I have this after running:
> > > `Traceback (most recent call last): File "E:\deflicker\src\stage1_neural_atlas.py", line 10, in <module> from src.models.stage_1.implicit_neural_networks import IMLP ModuleNotFoundError: No module named 'src' Traceback (most recent call last): File "E:\deflicker\src\neural_filter_and_refinement.py", line 6, in <module> import src.models.network_filter as net ModuleNotFoundError: No module named 'src'`
> > 
> > 
> > Have you found the solution? I also got this same problem, still have not figured it out yet.
> 
> Solution is to remove prefix src from every line of code where it occurs. For example src.models.network_filter -> models.network_filter.

Got it now, thanks so much!

**Comment by gvonkreisler** [comment]
Get lost of most off the =xx.xx,xx statements runs very fine with newer versions
