### ISSUE TITLE
How can i fix the error

### ISSUE THREAD

**Issue by panda66666666** [ChenyangLEI/All-In-One-Deflicker#18]
frame=   80 fps=0.0 q=-0.0 Lsize=N/A time=00:00:08.00 bitrate=N/A speed=42.5x    
video:15063kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Traceback (most recent call last):
  File "/root/All-In-One-Deflicker/src/stage1_neural_atlas.py", line 274, in <module>
    cmd = "python src/preprocess_optical_flow.py --vid-path %s --gpu %s " % (vid_path, select_gpu)
NameError: name 'select_gpu' is not defined
Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', fps=10, video_name='Winter_Scenes_in_Holland', gpu=0)
Load ./pretrained_weights/local_refinement_net.pth
Traceback (most recent call last):
  File "/root/All-In-One-Deflicker/src/neural_filter_and_refinement.py", line 73, in <module>
    assert len(style_names) == len(content_names), "the number of style frames is different from the number of content frames"
AssertionError: the number of style frames is different from the number of content frames

**Comment by jamesmgg** [comment]
I'm having the same error

**Comment by markrmiller** [comment]
Here is what I do, change deflicker to your env name:

export CUDA_VISIBLE_DEVICES=0
export LIBRARY_PATH=/opt/conda/envs/deflicker/include
export LD_LIBRARY_PATH=/opt/conda/envs/deflicker/lib
export CUDA_HOME=/opt/conda/envs/deflicker

As I want pytorch 2, I also uninstall pytorch with conda uninstall pytorch and then pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
conda install -c nvidia cudnn

Then run.

**Comment by markrmiller** [comment]
Oh, right, and as for the assert, I just comment it out.

**Comment by gvonkreisler** [comment]
Simply disable the if statement will do the trick
