### ISSUE TITLE
[BUG] Using image folder path

### ISSUE THREAD

**Issue by TangrisJones** [ChenyangLEI/All-In-One-Deflicker#2]
Hey team, thanks for open sourcing this awesome code! I'm really excited to try it out. 

I got it to work on video, but I decided to try to use image frames as well. Seems like I'm getting an error with it. Heres the full log including the error: 

```
Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', fps=10, gpu=0, video_frame_folder='/home/jupyter/repo/All-In-One-Deflicker/data/test/bunny_nadia_v4-face-frames-0_200', video_name=None)
input folder ./data/test/bunny_nadia_v4-face-frames-0_200 exist
python src/preprocess_optical_flow.py --vid-path data/test/bunny_nadia_v4-face-frames-0_200 --gpu 0 
computing flow:   0%|                                                                  | 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "src/preprocess_optical_flow.py", line 48, in <module>
    preprocess(args=args)
  File "src/preprocess_optical_flow.py", line 29, in preprocess
    flow12 = raft_wrapper.compute_flow(im1, im2)
  File "/home/jupyter/repo/All-In-One-Deflicker/src/models/stage_1/raft_wrapper.py", line 70, in compute_flow
    _, flow12 = self.model(im1, im2, iters=20, test_mode=True)
  File "/opt/conda/envs/deflicker/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/repo/All-In-One-Deflicker/src/models/stage_1/core/raft.py", line 104, in forward
    fmap1, fmap2 = self.fnet([image1, image2])        
  File "/opt/conda/envs/deflicker/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/repo/All-In-One-Deflicker/src/models/stage_1/core/extractor.py", line 176, in forward
    x = self.conv1(x)
  File "/opt/conda/envs/deflicker/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/deflicker/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/envs/deflicker/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 4, 768, 768] to have 3 channels, but got 4 channels instead
Traceback (most recent call last):
  File "src/stage1_neural_atlas.py", line 279, in <module>
    main(json.load(f), args)
  File "src/stage1_neural_atlas.py", line 109, in main
    resy, resx, maximum_number_of_frames, data_folder, True,  True, vid_root, vid_name)
  File "/home/jupyter/repo/All-In-One-Deflicker/src/models/stage_1/unwrap_utils.py", line 145, in load_input_data_single
    flow12 = np.load(flow12_fn)
  File "/opt/conda/envs/deflicker/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/bunny_nadia_v4-face-frames-0_200_flow/output_frame_001.png_output_frame_002.png.npy'
Namespace(ckpt_filter='./pretrained_weights/neural_filter.pth', ckpt_local='./pretrained_weights/local_refinement_net.pth', gpu=0, video_name='bunny_nadia_v4-face-frames-0_200')
Load ./pretrained_weights/local_refinement_net.pth
Traceback (most recent call last):
  File "src/neural_filter_and_refinement.py", line 72, in <module>
    assert len(style_names) == len(content_names), "the number of style frames is different from the number of content frames"
AssertionError: the number of style frames is different from the number of content frames
```

I'm not fully sure what it means, but it looks like the following is causing the issue: 

1) RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[2, 4, 768, 768] to have 3 channels, but got 4 channels instead -> this seems to break writing the .npy files? 
2) because of that, there seems to be a fatal bug: AssertionError: the number of style frames is different from the number of content frames

Any ideas on how to fix? My total guess is perhaps because my images are PNG, its reading an extra alpha channel as the 4th channel, when it expects only 3? I'm not sure though...

Please let me know if you need any extra info. Thanks alot!

**Comment by ChenyangLEI** [comment]
Yes, I think you are correct. It is because your images are PNG and there are 4 channels for your PNG images.  

Let us fix this bug.

**Comment by robbinhan** [comment]
Excuse me when can fix this bug, I also encountered this problem

**Comment by ChenyangLEI** [comment]
> Excuse me when can fix this bug, I also encountered this problem

Can you share your video so that we can test it? Thanks.

**Comment by robbinhan** [comment]
I wrote a Python script that converts PNG images into RGB 3-channel
