### ISSUE TITLE
Download pretrained ckpt does not work - Google Colab example possible?

### ISSUE THREAD

**Issue by herrartist** [ChenyangLEI/All-In-One-Deflicker#30]
Download pretrained ckpt does not work. I also don't know in which folder to put the pretrained ckpt. Can you make a Google Colab Github example, please?

**Comment by mycomedico** [comment]
I am trying to run this on google colab as well, but get the following errror:  

Traceback (most recent call last):
  File "/content/All-in-one-Deflicker/src/stage1_neural_atlas.py", line 10, in <module>
    from src.models.stage_1.implicit_neural_networks import IMLP
ModuleNotFoundError: No module named 'src'
Traceback (most recent call last):
  File "/content/All-in-one-Deflicker/src/neural_filter_and_refinement.py", line 6, in <module>
    import src.models.network_filter as net
ModuleNotFoundError: No module named 'src'

**Comment by mycomedico** [comment]
I got the example working on colab with the following set of commands:

! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh
! wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh
! bash ./Miniconda3-py37_4.12.0-Linux-x86_64.sh -b -f -p /usr/local/
!git clone https://github.com/ChenyangLEI/All-in-one-Deflicker
!conda env update -n base -f All-in-one-Deflicker/environment.yml
%cd All-in-one-Deflicker/
!git clone https://github.com/ChenyangLEI/cvpr2023_deflicker_public_folder
%mv cvpr2023_deflicker_public_folder/pretrained_weights ./ && rm -r cvpr2023_deflicker_public_folder
!export PYTHONPATH=$PWD
%mkdir -p /usr/local/lib/python3.10/site-packages/src
%cp -r "src/"* /usr/local/lib/python3.10/site-packages/src
!python test.py --video_name data/test/Winter_Scenes_in_Holland.mp4
